version: '3.11'

services:
  web:
    build: ./NewsPaper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./NewsPaper/:/usr/src/NewsPaper/
    ports:
      - 8000:8000
    env_file:
      - .env