# Generated by Django 4.2.1 on 2023-05-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='author',
            name='nick_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
