# Generated by Django 4.2.1 on 2023-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_nick_name_author_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nick_name',
            field=models.CharField(default='Автор', max_length=255, null=True),
        ),
    ]
